python -m pip install --user  --upgrade pip
pip install subprocess
pip install pynput
pip install webbrowser
pip install selenium
pip install webdriver
pip install Controller
pip install requests
pip install hashlib
pip install bcrypt
pip install tkinter
pip install SpeechRecognition
pip install pyaudio
pip install webdriver_manager
pip install numpy
pip install pyautogui
pip install opencv-python
pip install Pillow
pip install pyaudio
pip install screen-recorder-python
pip install tkcalendar